# Generated by Django 4.2.30 on 2026-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_application_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_job_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
