# Generated by Django 4.2.29 on 2026-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('insights', models.JSONField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_matching_matchresult',
            },
        ),
    ]
