# Generated by Django 4.2.30 on 2026-04-26 09:29

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_full_name_profile_github_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/employers/', validators=[apps.users.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/jobseekers/', validators=[apps.users.models.validate_file_size]),
        ),
    ]
