import re
from typing import List, Dict, Set


class SkillNormalizer:
    SKILL_MAP = {
        "js": "javascript",
        "node": "nodejs",
        "node.js": "nodejs",
        "reactjs": "react",
        "ts": "typescript",
        "py": "python",
        "django rest framework": "django",
        "drf": "django",
        "ml": "machine learning",
        "ai": "artificial intelligence",
        "vuejs": "vue",
        "angularjs": "angular",
        "aws": "amazon web services",
        "gcp": "google cloud platform",
        "css3": "css",
        "html5": "html",
        "es6": "javascript",
        "ecmascript": "javascript",
        "sql": "structured query language",
        "nosql": "no sql",
        "mongodb": "mongo",
        "postgresql": "postgres",
        "pg": "postgres",
        "mysql": "my sql",
        "redis": "red is",
        "k8s": "kubernetes",
        "kube": "kubernetes",
        "tf": "terraform",
        "ci/cd": "cicd",
        "docker-compose": "docker compose",
        "gitlab": "git lab",
        "github": "git hub",
        "jira": "ji ra",
        "confluence": "con fluence",
        "restful": "rest",
        "graphql": "graph ql",
        "grpc": "g rpc",
        "websocket": "web socket",
        "http": "hyper text transfer protocol",
        "https": "hyper text transfer protocol secure",
        "api": "application programming interface",
        "ui/ux": "ui ux",
        "fullstack": "full stack",
        "frontend": "front end",
        "backend": "back end",
        "devops": "dev ops",
        "mlops": "ml ops",
        "data science": "data-science",
        "data-science": "data science",
        "deep learning": "deep-learning",
        "deep-learning": "deep learning",
        "nlp": "natural language processing",
        "cv": "computer vision",
        "rpa": "robotic process automation",
        "iot": "internet of things",
        "ar": "augmented reality",
        "vr": "virtual reality",
        "mr": "mixed reality",
        "xr": "extended reality",
        "saas": "software as a service",
        "paas": "platform as a service",
        "iaas": "infrastructure as a service",
        "fpga": "field programmable gate array",
        "gpu": "graphics processing unit",
        "cpu": "central processing unit",
        "ram": "random access memory",
        "ssd": "solid state drive",
        "hdd": "hard disk drive",
        "os": "operating system",
        "sdk": "software development kit",
        "ide": "integrated development environment",
        "cli": "command line interface",
        "gui": "graphical user interface",
        "api gateway": "apigateway",
        "microservices": "micro service",
        "micro service": "microservices",
        "serverless": "server less",
        "lambda": "aws lambda",
        "ec2": "amazon elastic compute cloud",
        "s3": "amazon simple storage service",
        "rds": "amazon relational database service",
        "dynamodb": "amazon dynamo db",
        "elasticache": "amazon elasticache",
        "cloudfront": "amazon cloudfront",
        "route53": "amazon route 53",
        "vpc": "virtual private cloud",
        "iam": "identity and access management",
        "kms": "key management service",
        "sns": "simple notification service",
        "sqs": "simple queue service",
        "athena": "amazon athena",
        "redshift": "amazon redshift",
        "emr": "amazon emr",
        "glue": "aws glue",
        "kinesis": "amazon kinesis",
        "cognito": "amazon cognito",
        "api-gateway": "api gateway",
        "cloudformation": "cloud formation",
        "elastic beanstalk": "elasticbeanstalk",
        "lightsail": "amazon lightsail",
        "ecs": "amazon elastic container service",
        "eks": "amazon elastic kubernetes service",
        "fargate": "aws fargate",
        "app runner": "apprunner",
        "amplify": "aws amplify",
        "mobile hub": "mobilehub",
        "pinpoint": "amazon pinpoint",
        "ses": "simple email service",
        "workmail": "amazon workmail",
        "chime": "amazon chime",
        "connect": "amazon connect",
        "lex": "amazon lex",
        "polly": "amazon polly",
        "transcribe": "amazon transcribe",
        "translate": "amazon translate",
        "comprehend": "amazon comprehend",
        "rekognition": "amazon rekognition",
        "textract": "amazon textract",
        "forensics": "amazon forensics",
        "macie": "amazon macie",
        "guardduty": "amazon guardduty",
        "inspector": "amazon inspector",
        "trusted advisor": "trustedadvisor",
        "config": "aws config",
        "cloudtrail": "cloud trail",
        "cloudwatch": "cloud watch",
        "x-ray": "xray",
        "vpc flow logs": "vpcflowlogs",
        "direct connect": "directconnect",
        "vpn": "virtual private network",
        "transit gateway": "transitgateway",
        "private link": "privatelink",
        "nat gateway": "natgateway",
        "internet gateway": "internetgateway",
        "elastic ip": "elasticip",
        "eip": "elastic ip",
        "placement group": "placementgroup",
        "spot instance": "spotinstance",
        "reserved instance": "reservedinstance",
        "on-demand": "ondemand",
        "dedicated host": "dedicatedhost",
        "dedicated instance": "dedicatedinstance",
        "capacity reservation": "capacityreservation",
        "launch template": "launchtemplate",
        "launch configuration": "launchconfiguration",
        "auto scaling": "autoscaling",
        "asg": "auto scaling group",
        "elb": "elastic load balancer",
        "alb": "application load balancer",
        "nlb": "network load balancer",
        "clb": "classic load balancer",
        "target group": "targetgroup",
        "health check": "healthcheck",
        "sticky session": "stickysession",
        "ssl certificate": "sslcertificate",
        "tls certificate": "tlscertificate",
        "acm": "aws certificate manager",
        "certificate manager": "acm",
        "waf": "web application firewall",
        "shield": "aws shield",
        "firewall manager": "firewallmanager",
        "security groups": "securitygroups",
        "nacl": "network access control list",
        "network acl": "nacl",
        "key pair": "keypair",
        "ssh key": "sshkey",
        "instance profile": "instanceprofile",
        "iam role": "iamrole",
        "iam user": "iamuser",
        "iam group": "iamgroup",
        "iam policy": "iampolicy",
        "managed policy": "managedpolicy",
        "inline policy": "inlinepolicy",
        "sso": "single sign-on",
        "ad": "active directory",
        "ldap": "lightweight directory access protocol",
        "saml": "security assertion markup language",
        "oidc": "openid connect",
        "oauth": "open authorization",
        "oauth2": "oauth 2.0",
        "jwt": "json web token",
        "jwe": "json web encryption",
        "jws": "json web signature",
        "jwk": "json web key",
        "jwks": "json web key set",
        "pem": "privacy enhanced mail",
        "der": "distinguished encoding rules",
        "cer": "certificate",
        "crt": "certificate",
        "key": "private key",
        "csr": "certificate signing request",
        "ca": "certificate authority",
        "pki": "public key infrastructure",
        "hsm": "hardware security module",
        "tpm": "trusted platform module",
        "yubikey": "yubi key",
        "fido": "fast identity online",
        "u2f": "universal 2nd factor",
        "mfa": "multi-factor authentication",
        "2fa": "two-factor authentication",
        "totp": "time-based one-time password",
        "hotp": "hash-based one-time password",
        "sms": "short message service",
        "email": "electronic mail",
        "push notification": "pushnotification",
        "webhook": "web hook",
        "callback": "call back",
        "polling": "poll",
        "long polling": "longpolling",
        "websocket": "web socket",
        "socket.io": "socketio",
        "signalr": "signal r",
        "socket cluster": "socketcluster",
        "deepstream": "deepstream hub",
        "mqtt": "message queuing telemetry transport",
        "amqp": "advanced message queuing protocol",
        "stomp": "streaming text oriented messaging protocol",
        "coap": "constrained application protocol",
        "xmpp": "extensible messaging and presence protocol",
        "irc": "internet relay chat",
        "matrix": "matrix protocol",
        "activitypub": "activity pub",
        "rss": "really simple syndication",
        "atom": "atom syndication format",
        "json-feed": "json feed",
        "opml": "outline processor markup language",
        "h-feed": "h feed",
        "h-entry": "h entry",
        "h-card": "h card",
        "h-event": "h event",
        "h-geo": "h geo",
        "h-product": "h product",
        "h-review": "h review",
        "h-recipe": "h recipe",
        "h-resume": "h resume",
        "h-audio": "h audio",
        "h-video": "h video",
        "microformats": "micro formats",
        "microdata": "micro data",
        "rdfa": "resource description framework in attributes",
        "schema.org": "schemaorg",
        "json-ld": "json linked data",
        "turtle": "terse rdf triple language",
        "n-triples": "n triples",
        "n-quads": "n quads",
        "trig": "trig rdf",
        "sparql": "sparql protocol and rdf query language",
        "graphql": "graph ql",
        "rest": "representational state transfer",
        "soap": "simple object access protocol",
        "xml-rpc": "xml remote procedure call",
        "json-rpc": "json remote procedure call",
        "gql": "graphql",
        "graphiql": "graphi ql",
        "apollo": "apollo graphql",
        "relay": "relay graphql",
        "urql": "universal react query library",
        "fetch": "fetch api",
        "axios": "axios http client",
        "xhr": "xmlhttprequest",
        "ajax": "asynchronous javascript and xml",
        "websocket": "web socket",
        "eventsource": "event source",
        "serviceworker": "service worker",
        "webworker": "web worker",
        "sharedworker": "shared worker",
        "worklet": "work let",
        "blob": "binary large object",
        "file": "file api",
        "filesystem": "file system api",
        "indexeddb": "indexed db",
        "web sql": "web sql database",
        "localstorage": "local storage",
        "sessionstorage": "session storage",
        "cookies": "http cookies",
        "cache": "cache api",
        "cache-storage": "cache storage api",
        "storage": "storage api",
        "quota": "quota management api",
        "filesystem": "file system access api",
        "clipboard": "clipboard api",
        "notifications": "notifications api",
        "push": "push api",
        "vibration": "vibration api",
        "geolocation": "geolocation api",
        "orientation": "device orientation api",
        "motion": "device motion api",
        "ambient light": "ambient light sensor",
        "battery": "battery status api",
        "network": "network information api",
        "connection": "network information api",
        "bluetooth": "web bluetooth",
        "usb": "web usb",
        "nfc": "web nfc",
        "serial": "web serial",
        "hid": "web hid",
        "gamepad": "gamepad api",
        "vr": "web xr device api",
        "ar": "web xr device api",
        "media": "media devices api",
        "capture": "media capture and streams api",
        "recorder": "media recorder api",
        "source": "media source api",
        "session": "media session api",
        "capabilities": "media capabilities api",
        "keys": "media key system",
        "encryption": "media encryption",
        "streaming": "media streaming",
        "webrtc": "web real-time communication",
        "webrtc-datachannel": "webrtc data channel",
        "sdp": "session description protocol",
        "ice": "interactive connectivity establishment",
        "stun": "session traversal utilities for nat",
        "turn": "traversal using relays around nat",
        "dtls": "datagram transport layer security",
        "srtp": "secure real-time transport protocol",
        "rtcp": "real-time transport control protocol",
        "rtp": "real-time transport protocol",
        "h264": "h.264",
        "h265": "h.265",
        "vp8": "vp8",
        "vp9": "vp9",
        "av1": "av1",
        "opus": "opus codec",
        "aac": "aac codec",
        "mp3": "mp3 codec",
        "vorbis": "vorbis codec",
        "flac": "flac codec",
        "wav": "wav codec",
        "ogg": "ogg container",
        "webm": "webm container",
        "mp4": "mp4 container",
        "mov": "mov container",
        "avi": "avi container",
        "mkv": "mkv container",
        "flv": "flv container",
        "wmv": "wmv container",
        "rm": "rm container",
        "rmvb": "rmvb container",
        "3gp": "3gp container",
        "3g2": "3g2 container",
        "m4v": "m4v container",
        "m4a": "m4a container",
        "m4b": "m4b container",
        "m4p": "m4p container",
        "m4r": "m4r container",
        "caf": "caf container",
        "aiff": "aiff container",
        "au": "au container",
        "snd": "snd container",
        "ra": "ra container",
        "wma": "wma container",
        "asf": "asf container",
        "ts": "ts container",
        "mts": "mts container",
        "m2ts": "m2ts container",
        "ps": "ps container",
        "vob": "vob container",
        "evo": "evo container",
        "ifo": "ifo container",
        "bup": "bup container",
        "divx": "divx container",
        "xvid": "xvid container",
        "mk3d": "mk3d container",
        "webp": "webp image",
        "avif": "avif image",
        "heif": "heif image",
        "heic": "heic image",
        "jpeg": "jpeg image",
        "jpg": "jpeg image",
        "png": "png image",
        "gif": "gif image",
        "bmp": "bmp image",
        "tiff": "tiff image",
        "tif": "tiff image",
        "svg": "svg image",
        "ico": "ico image",
        "webp": "webp image",
        "apng": "apng image",
        "mng": "mng image",
        "jng": "jng image",
        "flif": "flif image",
        "bpg": "bpg image",
        "pjpeg": "progressive jpeg",
        "pjpg": "progressive jpeg",
        "pdf": "pdf document",
        "doc": "word document",
        "docx": "word document",
        "xls": "excel spreadsheet",
        "xlsx": "excel spreadsheet",
        "ppt": "powerpoint presentation",
        "pptx": "powerpoint presentation",
        "odt": "opendocument text",
        "ods": "opendocument spreadsheet",
        "odp": "opendocument presentation",
        "rtf": "rich text format",
        "txt": "plain text",
        "md": "markdown",
        "markdown": "markdown",
        "tex": "latex",
        "latex": "latex",
        "bib": "bibtex",
        "bibtex": "bibtex",
        "rst": "restructuredtext",
        "restructuredtext": "restructuredtext",
        "adoc": "asciidoc",
        "asciidoc": "asciidoc",
        "wiki": "wiki markup",
        "mediawiki": "mediawiki markup",
        "creole": "creole markup",
        "textile": "textile markup",
        "org": "org mode",
        "orgmode": "org mode",
        "epub": "epub format",
        "mobi": "mobi format",
        "azw": "amazon kindle format",
        "azw3": "amazon kindle format",
        "kfx": "amazon kindle format",
        "djvu": "djvu format",
        "fb2": "fb2 format",
        "lit": "lit format",
        "pdb": "pdb format",
        "tcr": "tcr format",
        "lrf": "lrf format",
        "rb": "rocketbook format",
        "snb": "snb format",
    }

    @staticmethod
    def normalize(skill: str) -> str:
        skill = skill.lower().strip()
        skill = re.sub(r'[^\w\s]', '', skill)
        skill = re.sub(r'\s+', ' ', skill)
        return SkillNormalizer.SKILL_MAP.get(skill, skill)

    @staticmethod
    def tokenize(skills: str) -> List[str]:
        skills = skills.lower()
        skills = re.sub(r'[^\w\s,]', '', skills)
        skill_list = [s.strip() for s in skills.split(',')]
        skill_list = [SkillNormalizer.normalize(s) for s in skill_list if s]
        return skill_list

    @staticmethod
    def expand_skills(skills: List[str], embedding_service, threshold: float = 0.6) -> List[str]:
        expanded = set(skills)
        for skill in skills:
            similar = embedding_service.find_similar_skills(skill, threshold)
            expanded.update(similar)
        return list(expanded)
