# Generated by Django 4.2.30 on 2026-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='filled_positions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
