# Generated by Django 4.2.29 on 2026-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applications_application',
            },
        ),
    ]
